import { Component } from '@angular/core';
import { MatTableModule } from '@angular/material/table';
import { Job } from '../model'


const ELEMENT_DATA: Job[] = [
  { id: 1, title: 'Apotheker/in', desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et', category: 'Akademische Berufe | Apotheker/innen, Pharmazeuten/Pharmazeutinnen - hoch komplexe Tätigkeiten', offer: 3 },
  { id: 2, title: 'Architekt/in', desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et', category: 'Akademische Berufe | Berufe in der Architektur - hoch komplexe Tätigkeiten', offer: 2 },
  { id: 3, title: 'Arzt/Ärztin', desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et', category: 'Akademische Berufe | Ärzte/Ärztinnen (ohne Spezialisierung) - hoch komplexe Tätigkeiten', offer: 5 },
  { id: 4, title: 'Buchhändler', desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et', category: 'Betriebliche, duale Ausbildung | Berufe im Buchhandel - fachlich ausgerichtete Tätigkeiten', offer: 0 },
  { id: 5, title: 'Chemielaborant/in', desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et', category: 'Betriebliche, duale Ausbildung | Berufe im chemisch-technischen Laboratorium - fachlich ausgerichtete Tätigkeiten', offer: 0 },
  { id: 6, title: 'Dachdecker/in', desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et', category: 'Betriebliche, duale Ausbildung | Berufe in der Dachdeckerei - fachlich ausgerichtete Tätigkeiten', offer: 0 },
  { id: 7, title: 'Gesundheits- und Krankenpflegehelfer/in', desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et', category: 'Schulische Ausbildung | Berufe in der Gesundheits- und Krankenpflege (ohne Spezialisierung) - Helfer-/Anlerntätigkeiten', offer: 0 },
  { id: 8, title: 'Goldschmied/in', desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et', category: 'Betriebliche, duale Ausbildung | Berufe in der kunsthandwerklichen Schmuckwarenherstellung, Edelstein- und Edelmetallbearbeitung - fachlich ausgerichtete Tätigkeiten', offer: 0 },
  { id: 9, title: 'Grafikdesigner/in', desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et', category: 'Sonstige Ausbildung | Berufe im Grafik-, Kommunikations- und Fotodesign - komplexe Spezialistentätigkeiten', offer: 0 },
  { id: 10, title: 'Koch/Köchin', desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et', category: 'Betriebliche, duale Ausbildung | Köche/Köchinnen (ohne Spezialisierung) - fachlich ausgerichtete Tätigkeiten', offer: 0 },
  { id: 11, title: 'Lehrer/in', desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et', category: 'Sonstige Ausbildung | Lehrkräfte in der Sekundarstufe - hoch komplexe Tätigkeiten', offer: 8 },
  { id: 12, title: 'Schornsteinfeger/in', desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et', category: 'Betriebliche, duale Ausbildung | Schornsteinfeger/innen - fachlich ausgerichtete Tätigkeiten', offer: 0 },
  { id: 13, title: 'Sozialarbeiter/in', desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et', category: 'Akademische Berufe | Berufe in der Sozialarbeit und Sozialpädagogik - hoch komplexe Tätigkeiten', offer: 11 },
  { id: 14, title: 'Tankwart/in', desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et', category: 'Betriebliche, duale Ausbildung | Berufe im Verkauf (sonstige spezifische Tätigkeitsangabe) - fachlich ausgerichtete Tätigkeiten', offer: 0 },
  { id: 15, title: 'Veranstaltungsfachkraft', desc: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et', category: 'Betriebliche, duale Ausbildung | Berufe in der Veranstaltungs- und Bühnentechnik - fachlich ausgerichtete Tätigkeiten', offer: 4 }
];

@Component({
  selector: 'app-table',
  templateUrl: './table.component.html',
  styleUrls: ['./table.component.scss']
})
export class TableComponent
{
  dataSource = ELEMENT_DATA;

   infoText: boolean|string = "Bitte betrachte die Vorschläge nur als Anregung, scrolle gerne nach unten um weitere Ergebnisse zu finden. Noch wurden nicht alle in Deutschland anerkannten Ausbildungen und Berufen eingestuft. Die Datenbasis für die Errechnung wird durch die Nutzung jedoch laufend verbessert. Du hilfst uns, wenn Du zu den Top 10 oder 20 Vorschlägen bei jedem einzelnen Beruf auf („Mag ich nicht“) klickst wenn dieser nicht passt. Die Berufe die Du dir gut vorstellen kannst, bitte mit („Mag ich“) als Favorit markieren."
  warningText:boolean|string = "Du hast den Fragebogen noch nicht komplett ausgefüllt. Die hier angezeigten Berufsvorschläge berücksichtigen nur Deine bisherigen Antworten und sind vermutlich noch nicht optimal."

 /*  infoText:boolean|any;
  warningText:boolean|any
 */
  showInfoIcon = false;
  showWarningIcon = false;
  onClickInfo(){
this.infoText
  }

  onClickWarning(){
this.warningText
  }

}
